// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTm0uPDJrzwPQwsXEp_ELzUcLbGrFTFkQ',
    appId: '1:342246714374:web:db77afa38ede1ef698a787',
    messagingSenderId: '342246714374',
    projectId: 'device-streaming-34aa2596',
    authDomain: 'device-streaming-34aa2596.firebaseapp.com',
    storageBucket: 'device-streaming-34aa2596.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5DvnJiBulFBQyC6-eDWzYxisquIejNKQ',
    appId: '1:342246714374:android:c39f08390079823298a787',
    messagingSenderId: '342246714374',
    projectId: 'device-streaming-34aa2596',
    storageBucket: 'device-streaming-34aa2596.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoif8Bz0UeF4qjtLpb1YVDQQovbuYXhY0',
    appId: '1:342246714374:ios:b1be4802173f170698a787',
    messagingSenderId: '342246714374',
    projectId: 'device-streaming-34aa2596',
    storageBucket: 'device-streaming-34aa2596.firebasestorage.app',
    iosBundleId: 'com.digitalabcs.textdecoder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoif8Bz0UeF4qjtLpb1YVDQQovbuYXhY0',
    appId: '1:342246714374:ios:3b6050b80e1efb4798a787',
    messagingSenderId: '342246714374',
    projectId: 'device-streaming-34aa2596',
    storageBucket: 'device-streaming-34aa2596.firebasestorage.app',
    iosBundleId: 'com.example.textDecoder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTm0uPDJrzwPQwsXEp_ELzUcLbGrFTFkQ',
    appId: '1:342246714374:web:fd8ebed4b8385a2798a787',
    messagingSenderId: '342246714374',
    projectId: 'device-streaming-34aa2596',
    authDomain: 'device-streaming-34aa2596.firebaseapp.com',
    storageBucket: 'device-streaming-34aa2596.firebasestorage.app',
  );
}
